name: QGIS Plugin Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    env:
      QGIS_VERSION: 3.34  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Assurez-vous que la version correspond à celle supportée par QGIS

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg software-properties-common
        # Ajouter le dépôt QGIS
        sudo sh -c "echo 'deb https://qgis.org/debian $(lsb_release -c -s) main' > /etc/apt/sources.list.d/qgis.list"
        wget -qO - https://qgis.org/downloads/qgis-2023.gpg.key | sudo apt-key add -
        sudo apt-get update
        # Installer QGIS et ses dépendances
        sudo apt-get install -y qgis python3-qgis qgis-plugin-grass

    - name: Set QGIS environment variables
      run: |
        echo "export QGIS_PREFIX_PATH=/usr" >> $GITHUB_ENV
        echo "export PYTHONPATH=/usr/share/qgis/python:$PYTHONPATH" >> $GITHUB_ENV
        echo "export PATH=/usr/bin:$PATH" >> $GITHUB_ENV

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assurez-vous d'avoir un fichier requirements.txt

    - name: Run Tests
      run: |
        # Exemple avec pytest
        pytest tests/
